tap "beeftornado/rmtree"
tap "charmbracelet/tap"
tap "gromgit/fuse"
tap "he3-app/he3"
tap "homebrew-ffmpeg/ffmpeg"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/services"
tap "mac-cleanup/mac-cleanup-py"
tap "mongodb/brew"
tap "nextdns/tap"
tap "redis-stack/redis-stack"
tap "sourcegraph/src-cli"
tap "zurawiki/brews"
brew "ack"
brew "ca-certificates"
brew "sqlite"
brew "glib"
brew "aria2"
brew "asitop"
brew "at-spi2-core"
brew "awscli"
brew "b2-tools"
brew "bat"
brew "bcftools"
brew "blueutil"
brew "node"
brew "bower"
brew "cheat"
brew "chezmoi"
brew "cmake"
brew "ctop"
brew "curl"
brew "dhcpdump"
brew "dialog"
brew "direnv"
brew "dnstop"
brew "doctl"
brew "duti"
brew "exiftool"
brew "gcc"
brew "gdk-pixbuf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glances"
brew "glfw"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "go"
brew "netpbm"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "gsettings-desktop-schemas"
brew "gtk+3"
brew "handbrake", link: false
brew "htop"
brew "jq"
brew "just"
brew "libarchive"
brew "libass"
brew "libffi"
brew "libzen"
brew "libmediainfo"
brew "libomp", link: true
brew "mandown"
brew "marked", link: false
brew "mas"
brew "micro"
brew "midnight-commander"
brew "mongocli"
brew "newt"
brew "noti"
brew "ollama"
brew "open-mpi"
brew "openapi-generator"
brew "openblas"
brew "openldap"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "poetry"
brew "poppler"
brew "proctools"
brew "psgrep"
brew "pstree"
brew "pv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.9"
brew "tcl-tk"
brew "python-tk@3.9"
brew "python@3.10"
brew "python@3.11"
brew "python@3.8"
brew "r", link: false
brew "redis"
brew "rename"
brew "rhash"
brew "ripgrep-all"
brew "rsync"
brew "rustup"
brew "smartmontools"
brew "speedtest-cli"
brew "srt"
brew "ssh-copy-id"
brew "terminal-notifier"
brew "tesseract"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "trash"
brew "tre-command"
brew "tree"
brew "uv"
brew "virtualenv"
brew "virtualenvwrapper"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zenity"
brew "zeromq"
brew "zplug"
brew "zsh"
brew "zsh-completions"
brew "charmbracelet/tap/mods"
brew "gromgit/fuse/sshfs-mac"
brew "homebrew-ffmpeg/ffmpeg/ffmpeg"
brew "mongodb/brew/mongodb-community"
brew "nextdns/tap/nextdns"
brew "sourcegraph/src-cli/src-cli"
cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "appcleaner"
cask "bartender"
cask "chatgpt"
cask "cheatsheet"
cask "chromedriver"
cask "chromium"
cask "coconutbattery"
cask "cursor"
cask "cyberduck"
cask "dbeaver-community"
cask "disk-expert"
cask "dockmate"
cask "dropbox"
cask "firefox"
cask "gephi"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "gpg-suite"
cask "handbrake"
cask "hazel"
cask "he3"
cask "iina"
cask "iterm2"
cask "jdownloader"
cask "keka"
cask "maccleaner-pro"
cask "maccy"
cask "macforge"
cask "macfuse"
cask "macpilot"
cask "macs-fan-control"
cask "marked"
cask "mongodb-compass"
cask "monitorcontrol"
cask "motrix"
cask "netiquette"
cask "orbstack"
cask "pieces-cli"
cask "postgres-unofficial"
cask "postman"
cask "processmonitor"
cask "quitter"
cask "r"
cask "raindropio"
cask "raycast"
cask "rocket"
cask "rstudio"
cask "setapp"
cask "sigmaos"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "stats"
cask "superhuman"
cask "tabtopus"
cask "taskexplorer"
cask "tor-browser"
cask "transmission"
cask "transmit"
cask "trunk-io"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "wireshark"
cask "xld"
cask "xquartz"
mas "1Password for Safari", id: 1569813296
mas "Actions", id: 1586435171
mas "AI Chat Bot", id: 6447312365
mas "Amphetamine", id: 937984704
mas "AutoMute", id: 1118136179
mas "Bear", id: 1091189122
mas "Bluetooth Inspector", id: 1509085044
mas "Boop", id: 1518425043
mas "Chat Unlimited & Ask Brutus AI", id: 6443925235
mas "Cleaner-App", id: 1013897218
mas "Codelime", id: 1622145140
mas "Copilot", id: 1447330651
mas "CopyQueue", id: 711074010
mas "Core Tunnel", id: 1354318707
mas "Craft", id: 1487937127
mas "CrystalFetch", id: 6454431289
mas "DaisyDisk", id: 411643860
mas "Disk Speed Test", id: 425264550
mas "Dropover", id: 1355679052
mas "Duplicate File Finder", id: 1032755628
mas "Fello AI", id: 6447705369
mas "FreeChat", id: 1084346074
mas "G App Launcher", id: 1543803459
mas "Highlights", id: 1498912833
mas "Home Assistant", id: 1099568401
mas "HTTPBot", id: 1232603544
mas "iWifi", id: 1476136371
mas "Keynote", id: 409183694
mas "LimeChat", id: 414030210
mas "Linkboard", id: 1612805234
mas "Magnet", id: 441258766
mas "Mail+ for Gmail", id: 1216244845
mas "Medis", id: 1579200037
mas "Meeter", id: 1510445899
mas "Mela", id: 1568924476
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Mountain Duck", id: 1024974133
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Parcel", id: 639968404
mas "PDFgear", id: 1615523079
mas "PhotoSweeper", id: 463362050
mas "ReadKit", id: 1615798039
mas "Shareful", id: 1522267256
mas "Shortery", id: 1594183810
mas "Sider", id: 6447783111
mas "Slack", id: 803453959
mas "Snippit", id: 1465481124
mas "Spark Desktop", id: 6445813049
mas "Speech Central", id: 1223093645
mas "Startup Disk Full Fixer", id: 1346655838
mas "Structured", id: 1499198946
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Telegram Lite", id: 946399090
mas "Templates for Numbers - DesiGN", id: 442666821
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Todoist", id: 585829637
mas "Universe", id: 1211437633
mas "Usage", id: 1561788435
mas "virtualOS", id: 1614659226
mas "WebSSH", id: 497714887
mas "WhaleDeck", id: 1581548562
mas "WiFi Scanner", id: 411680127
mas "WiFi Speed Test", id: 1455463454
vscode "aaron-bond.better-comments"
vscode "alefragnani.bookmarks"
vscode "alefragnani.project-manager"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "atishay-jain.all-autocomplete"
vscode "aykutsarac.jsoncrack-vscode"
vscode "bierner.markdown-mermaid"
vscode "bierner.markdown-preview-github-styles"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "cacher.cacher-vscode"
vscode "charliermarsh.ruff"
vscode "christian-kohler.path-intellisense"
vscode "codeium.codeium"
vscode "codestream.codestream"
vscode "codezombiech.gitignore"
vscode "codium.codium"
vscode "continue.continue"
vscode "ctf0.macros"
vscode "cxfksword.goto-documentation"
vscode "danielsanmedium.dscodegpt"
vscode "davidanson.vscode-markdownlint"
vscode "deerawan.vscode-dash"
vscode "dheovani.svg-viewer"
vscode "dmytrobaida.gpt-commit"
vscode "donjayamanne.git-extension-pack"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-environment-manager"
vscode "dotjoshjohnson.xml"
vscode "eamodio.gitlens"
vscode "easycodeai.chatgpt-gpt4-gpt3-vscode"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "foxundermoon.shell-format"
vscode "frhtylcn.pythonsnippets"
vscode "genieai.chatgpt-vscode"
vscode "gera2ld.markmap-vscode"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "goessner.mdmath"
vscode "googlecloudtools.cloudcode"
vscode "grapecity.gc-excelviewer"
vscode "gruntfuggly.shifter"
vscode "gruntfuggly.todo-tree"
vscode "hnw.vscode-auto-open-markdown-preview"
vscode "hoovercj.vscode-settings-cycler"
vscode "huggingface.huggingface-vscode"
vscode "ibm.output-colorizer"
vscode "inu1255.easy-snippet"
vscode "ionutvmi.path-autocomplete"
vscode "jabacchetta.vscode-essentials"
vscode "jakearl.search-editor-apply-changes"
vscode "james-yu.latex-workshop"
vscode "jasonlhy.hungry-delete"
vscode "jkjustjoshing.vscode-text-pastry"
vscode "johnpapa.vscode-peacock"
vscode "kaleidoscope-app.vscode-ksdiff"
vscode "kevinrose.vsc-python-indent"
vscode "lacroixdavid1.vscode-format-context-menu"
vscode "lightrun.lightrunplugin-saas"
vscode "lostintangent.vsls-whiteboard"
vscode "mathpix.vscode-mathpix-markdown"
vscode "mattflower.aider"
vscode "mechatroner.rainbow-csv"
vscode "meezilla.json"
vscode "merico.devchat"
vscode "merico.lang-bridge-vsc"
vscode "meshintelligenttechnologiesinc.pieces-vscode"
vscode "metaseed.metago"
vscode "metaseed.metajump"
vscode "metaseed.metaword"
vscode "mgesbert.python-path"
vscode "mhutchie.git-graph"
vscode "micnil.vscode-checkpoints"
vscode "mikestead.dotenv"
vscode "mikoz.black-py"
vscode "monokai.theme-monokai-pro-vscode"
vscode "morph.rift-vscode"
vscode "morrislaptop.vscode-open-in-sourcetree"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.autopep8"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.gather"
vscode "ms-python.mypy-type-checker"
vscode "ms-python.pylint"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.datawrangler"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.wordcount"
vscode "ms-vsliveshare.vsliveshare"
vscode "nhoizey.gremlins"
vscode "njpwerner.autodocstring"
vscode "njqdev.vscode-python-typehint"
vscode "oderwat.indent-rainbow"
vscode "percy.vscode-numpy-viewer"
vscode "peterschmalfeldt.explorer-exclude"
vscode "pkief.material-icon-theme"
vscode "pnp.polacode"
vscode "rdebugger.r-debugger"
vscode "reageyao.biosyntax"
vscode "redhat.fabric8-analytics"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "redjue.git-commit-plugin"
vscode "ritwickdey.liveserver"
vscode "sharat.vscode-brewfile"
vscode "sonarsource.sonarlint-vscode"
vscode "sourcegraph.cody-ai"
vscode "sourcegraph.sourcegraph"
vscode "stkb.rewrap"
vscode "streetsidesoftware.code-spell-checker"
vscode "tabnine.tabnine-vscode"
vscode "taldennis-unfoldai-chatgpt-copilot.unfoldai"
vscode "tamasfe.even-better-toml"
vscode "thedavej.night-owl-black"
vscode "tomoki1207.pdf"
vscode "trunk.io"
vscode "tushortz.python-extended-snippets"
vscode "ultram4rine.vscode-choosealicense"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-snippet.snippet"
vscode "vsls-contrib.gistfs"
vscode "vstirbu.vscode-mermaid-preview"
vscode "waderyan.gitblame"
vscode "xyz.local-history"
vscode "yzane.markdown-pdf"
vscode "yzhang.markdown-all-in-one"
vscode "ziyasal.vscode-open-in-github"
